###
DELETE http://localhost:4999/delete?id=8

###
POST http://localhost:4999/api/info?id=8
Content-Type: application/json

{
    "information": "my name is justin"
}

###
PUT  http://localhost:4999/api/?word=justin&banana=ripe

###
DELETE http://localhost:4999/delete/justin/cool
